### ISSUE TITLE
Setup repo

### ISSUE THREAD

**Issue by kiootic** [SkygearIO/auth-landing#3]
- [x] Setup linting & formatting
- [x] Setup CI
    - [x] Use GitHub Action
    - [x] Deploy to GitHub Pages on `master` update
- [x] Setup `staging` & `production` branch

**Comment by Arthelon** [comment]
Will tackle svelte linting/formatting with eslint/prettier

**Comment by Arthelon** [comment]
@kiootic is there a specific styleguide you would like to use for linting JavaScript files?

**Comment by kiootic** [comment]
We have a [eslint preset](https://github.com/oursky/eslint-oursky) maintained by @louischan-oursky used by other projects. Since we're not using TypeScript, we may not able to use it as-is. We can pick a subset of the rules from there.
