### ISSUE TITLE
[Landing, Mobile] Should not allow to type on textfield when the sub-menu is activated

### ISSUE THREAD

**Issue by hinshum** [SkygearIO/auth-landing#54]
## Environment:
- Testing platform: Safari
- Testing device: iPhone XS max
- Device OS version: iOS 13.3.1
- Testing environment: nightly

## Description:
Text can be enterred on the detailed page when the sub-menu is activated. This results in the overlapping of the text area of the sub-menu.

## Steps to reproduce:
1. Go to the webpage in mobile devices
2. Activate the sub-menu
3. Click into any text area and start typing

## Expected result:
Maybe just close the sub-menu when clicking the area of the landing page?

## Screenshot:
![Screen Shot 2020-05-29 at 4 16 42 PM](https://user-images.githubusercontent.com/29699339/83237644-ce4df200-a1c7-11ea-84f2-8a292694b982.png)

**Comment by Arthelon** [comment]
@koskosm for this task, I'm thinking of adding a shaded overlay that is shown across the page contents when the mobile menu is open. Similar to [this](https://blueprintjs.com/docs/#core/components/drawer)

When the overlay is clicked on then the mobile menu closes again.

Any thoughts?
