### ISSUE TITLE
[Landing, Edge] Landing page content cannot be viewed on Edge

### ISSUE THREAD

**Issue by hinshum** [SkygearIO/auth-landing#55]
## Environment:
- Testing platform: Edge
- Testing device: Laptop
- Device OS version: win10
- Testing environment: nightly

## Description:
Landing page content cannot be viewed on Edge. ‘Unexpected end of file’ message is shown.

## Steps to reproduce:
1. Go to the webpage on Edge

## Expected result:
Should show the content

## Screenshot:
![Screen Shot 2020-05-29 at 4 29 12 PM](https://user-images.githubusercontent.com/29699339/83238885-a8c1e800-a1c9-11ea-8f5f-e1912b4ffba3.png)
![edgeerror1](https://user-images.githubusercontent.com/29699339/83238891-ab244200-a1c9-11ea-9ca8-00909db44edf.PNG)
![edgeversion](https://user-images.githubusercontent.com/29699339/83238897-abbcd880-a1c9-11ea-877e-11a30beb65c9.PNG)

**Comment by Arthelon** [comment]
This issue seems to be related to the babel setup

**Comment by Arthelon** [comment]
@kiootic I just noticed that Edge is not included in the project's browserslist which could explain this error. 

https://github.com/SkygearIO/auth-landing/blob/master/package.json#L62

Do we have a recommended browserslist?

**Comment by kiootic** [comment]
We can add the latest 2 Edge version in browserslist.

**Comment by Arthelon** [comment]
Issue is related to the shimport dependency.

https://github.com/sveltejs/sapper/issues/657 

Removing the PrismJS imports from `CodeEditor` fixed the issue.

**Comment by kiootic** [comment]
Is it possible to produce a real static output instead? i.e. no JS script in output.

**Comment by Arthelon** [comment]
I don't think so. 

@kiootic This issue is taking some time for me to debug so I am going to disable syntax highlighting for now to get this working on IE11/Edge. Will come back to this later after more pressing issues.
