### ISSUE TITLE
[Landing, Mobile, iOS] Repeatedly clicking `copy code` will trigger a shadow at the bottom

### ISSUE THREAD

**Issue by hinshum** [SkygearIO/auth-landing#57]
Test with iPhone xs-max (13.3) - Safari landscape mode

ref: 0:10-0:18
https://drive.google.com/open?id=1exxckyhz4kC-xN8ilZ5Qmr7kY6Crcxjx

**Comment by kiootic** [comment]
This should be expected behavior: When a button is pressed down, it should be highlighted to provide UI feedback. It's same behavior as links.
