### ISSUE TITLE
Fix deployment

### ISSUE THREAD

**Issue by louischan-oursky** [SkygearIO/auth-landing#6]
If we visit https://skygeario.github.io/auth-landing/ and open the browser console, we can see resources cannot be loaded correctly. The referenced resources has hash in the file name but [the deployed resources do not](https://github.com/SkygearIO/auth-landing/tree/gh-pages).

**Comment by kiootic** [comment]
I think the cause is that it is assuming the website is hosted at root.

**Comment by louischan-oursky** [comment]
So we need to handle **both** cases.

**Comment by Arthelon** [comment]
We can modify the base URL according to this: https://sapper.svelte.dev/docs/#Base_URLs
