### ISSUE TITLE
Setup project structure

### ISSUE THREAD

**Issue by kiootic** [SkygearIO/auth-landing#7]
- Cleanup scaffolding pages
- Setup placeholder routes (with reference to design and the current website at https://skygear.io/)
- Setup placeholder common components (e.g. nav bar, footer)
- (optional) Setup CSS transpilation (SASS/LESS)

**Comment by louischan-oursky** [comment]
```
browserslist = [
    "last 2 chrome versions",
    "last 2 firefox versions",
    "Firefox ESR",
    "Android >= 5.0",
    "iOS >= 11",
    "Safari >= 11",
    "IE >= 11",
]
```
